package kotoba:application@1.0.0;

world application {
  export headers-edn-empty: func() -> string;
  export headers-edn-one: func(name: string, value: string) -> string;
  export http-header-edn-trust: func(name: string, value: string) -> string;
  export http-request-edn-trust: func(url: string, headers: string, body: string, timeout-str: string) -> string;
  export http-result-err-edn-trust: func(code: string, retryable-str: string) -> string;
  export http-result-ok-edn-trust: func(status-str: string, headers: string, body: string) -> string;
}
